author_id = "demo"
app_id = "chip8"
author_name = "Demo"
app_name = "CHIP-8"
lang = "rust"

[files]
main = { path = "Pong [Paul Vervalin, 1990].ch8", copy = true }
config = { path = "config.txt", copy = true }
